Move prover returns: exiting with verification errors
warning: Unused assignment to `y`. Consider removing or prefixing with an underscore: `_y`
   ┌─ tests/sources/functional/specs_in_fun.move:18:9
   │
18 │         y = x + 1;
   │         ^^^^^^^^^

warning: Unused assignment to `z`. Consider removing or prefixing with an underscore: `_z`
   ┌─ tests/sources/functional/specs_in_fun.move:33:9
   │
33 │         z = x + y;
   │         ^^^^^^^^^

warning: Unused assignment to `y`. Consider removing or prefixing with an underscore: `_y`
   ┌─ tests/sources/functional/specs_in_fun.move:51:9
   │
51 │         y = x + 1;
   │         ^^^^^^^^^

warning: Unused assignment to `z`. Consider removing or prefixing with an underscore: `_z`
   ┌─ tests/sources/functional/specs_in_fun.move:66:9
   │
66 │         z = x + y;
   │         ^^^^^^^^^

error: unknown assertion failed
   ┌─ tests/sources/functional/specs_in_fun.move:45:13
   │
45 │             assert x == y;
   │             ^^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/specs_in_fun.move:42: simple1_incorrect
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/specs_in_fun.move:43: simple1_incorrect
   =     at tests/sources/functional/specs_in_fun.move:45: simple1_incorrect

error: unknown assertion failed
   ┌─ tests/sources/functional/specs_in_fun.move:53:13
   │
53 │             assert x == y;
   │             ^^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/specs_in_fun.move:49: simple2_incorrect
   =         x = <redacted>
   =     at tests/sources/functional/specs_in_fun.move:51: simple2_incorrect
   =         <redacted> = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/specs_in_fun.move:53: simple2_incorrect

error: unknown assertion failed
   ┌─ tests/sources/functional/specs_in_fun.move:60:13
   │
60 │             assert x > y;
   │             ^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/specs_in_fun.move:57: simple3_incorrect
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/specs_in_fun.move:59: simple3_incorrect
   =     at tests/sources/functional/specs_in_fun.move:60: simple3_incorrect

error: unknown assertion failed
   ┌─ tests/sources/functional/specs_in_fun.move:69:13
   │
69 │             assert z > 2*x;
   │             ^^^^^^^^^^^^^^^
   │
   =     at tests/sources/functional/specs_in_fun.move:64: simple4_incorrect
   =         x = <redacted>
   =         y = <redacted>
   =     at tests/sources/functional/specs_in_fun.move:66: simple4_incorrect
   =         z = <redacted>
   =     at tests/sources/functional/specs_in_fun.move:68: simple4_incorrect
   =     at tests/sources/functional/specs_in_fun.move:69: simple4_incorrect
